config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/users/:id/my_play_dates' => 'play_dates#index', as: :my_play_dates
  get '/play_dates/past' => 'play_dates#past', as: :past_play_dates
  resources :users, only: [:new, :create, :show, :update, :edit] do
    resources :dogs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :play_dates, only: [:new, :create, :show, :update, :edit, :index, :destroy]
  resources :dog_play_dates, only: [:destroy, :create]
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/welcome' => 'welcome#welcome'
  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user, optional: true
  has_many :dog_play_dates
  has_many :play_dates, through: :dog_play_dates

  validates :name, presence: true
  # validates :age, numericality: true
  # validates :sex, presence: true
  # validates :weight, numericality: true
  # validates :aggressive_rating, numericality: true
  # validates :friendly_rating, numericality: true

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :require_login
  before_action :authorized?, only: [:edit, :update, :destroy, :new, :create]
  after_action :header_vary, only: [:show, :index]

  def index
    @dogs = find_user_by_id.dogs
    if find_user_by_id == current_user
      respond_to do |format|
        format.json { render json: @dogs }
        format.html { render 'dogs/index' }
      end
    else
      respond_to do |format|
        format.json { render json: @dogs }
        format.html { redirect_to welcome_path }
      end
    end
  end

  def new
    @dog = find_user_by_id.dogs.build
  end

  def create
    @dog = find_user_by_id.dogs.build(dog_params)
    save_dog_or_show_error
  end

  def show
    find_dog_by_id
    respond_to do |format|
      format.json { render json: @dog }
      format.html { render 'dogs/show' }
    end
  end

  def edit
    find_dog_by_id
  end

  def update
    find_dog_by_id.update(dog_params)
    redirect_to user_dog_path(current_user, @dog)
  end

  def destroy
    find_dog_by_id.dog_play_dates.each {|p| p.destroy }
    find_dog_by_id.destroy
    redirect_to user_dogs_path(current_user)
  end

  private

    def dog_params
      params.require(:dog).permit(:name, :sex, :breed, :age, :weight, :friendly_rating, :aggressive_rating, :fixed, :img)
    end

    def find_dog_by_id
      @dog = Dog.find(params[:id])
    end

    def save_dog_or_show_error
      if @dog.save
        redirect_to user_dog_path(current_user, @dog)
      else
        render :new
      end
    end
end

app/helpers/dogs_helper.rb
module DogsHelper

  def fixed_to_string(dog)
    dog.fixed ? "Yes" : "No"
  end

  def breeds_for_select
    url = "https://raw.githubusercontent.com/dariusk/corpora/master/data/animals/dogs.json"
    @breed ||= JSON.parse(open(url).read)["dogs"]
  end

  def dog_image(dog)
    dog.img == nil || dog.img == "" ? "dogs.png" : dog.img
  end

  def div_open_freq(i)
    (i % 3 == 0) || i == 0
  end

  def div_close_freq(i)
    (i + 1) % 3 == 0
  end

  def friendly_icons(dog)
    html_string = ""
    html_string.tap {
      dog.friendly_rating.times do
        html_string <<
        <<-HTML
          <i class="fas fa-smile yellow-text"></i>
        HTML
      end
      (10 - (dog.friendly_rating)).times do
        html_string <<
        <<-HTML
          <i class="fas fa-smile invert"></i>
        HTML
      end
    }
  end

  def aggressive_icons(dog)
    html_string = ""
    html_string.tap {
      dog.aggressive_rating.times do
        html_string <<
        <<-HTML
          <i class="fas fa-angry red-text"></i>
        HTML
      end
      (10 - (dog.aggressive_rating)).times do
        html_string <<
        <<-HTML
          <i class="fas fa-angry invert"></i>
        HTML
      end
    }
  end

  def has_no_play_dates?(dog)
    if !dog.play_dates.any?
      "#{dog.name} is not attending any playdates yet!"
    end
  end

end

app/views/dogs/_dog_grid.html.erb
<% dogs.all.each_with_index do |dog, i| %>
  <% if div_open_freq(i) %>
    <div class="row">
  <% end %>
  <% @dog = dog %>

    <%= yield(@dog) %>

  <% if div_close_freq(i)  %>
    </div>
  <% end %>
<% end %>

app/views/dogs/_dog_img_about.html.erb
<div class="col-lg-4 text-<%= align %> mb-4">

    <% if complete == true %>
      <h2 class="yellow-text"><%= dog.name %></h2>
    <% end %>

    <%= image_tag("#{dog_image(dog)}", class: "dog-img") %>

    <div class="<%= div_class %>">

      <% if complete == false %>
        <div class="bottom-text">
        <h3><a href="<%= user_dog_path(current_user, dog) %>" class="yellow-link"><%= dog.name %></a></h3>
      <% end %>

        <%= "#{dog.age} years old" if dog.age %> <br>
        <%= "#{dog.weight} lbs." if dog.weight %><br>
        <%= "#{dog.breed}" if dog.breed %><br>
        <%= "#{dog.sex}" if dog.sex %><br>

        <% if complete == true %>
          Fixed? <%= fixed_to_string(dog) %><br>

            How friendly?<br>
            <%= friendly_icons(dog).html_safe if dog.friendly_rating %><br>

            How aggressive?<br>
            <%= aggressive_icons(dog).html_safe if dog.aggressive_rating%><br>

        <% end %>

      <% if complete == false %>
        </div>
      <% end %>
    </div>
</div>

app/views/dogs/_new_dog_form.html.erb
<%= f.label :name %><br>
<%= f.text_field :name, class: "form-control-sm" %><br>

<%= f.label :sex %><br>
<div class="form-check">
  <%= f.radio_button "sex", "Male", class: "form-check-input" %>
  <%= f.label "Male", class: "form-check-label" %><br>
  <%= f.radio_button "sex", "Female", class: "form-check-input"  %>
  <%= f.label "Female", class: "form-check-label" %>
</div>

<%= f.label :breed %><br>
<%= f.text_field :breed, list: "dog_breeds", class: "form-control-sm" %>
<%== data_list("dog_breeds", breeds_for_select) %><br>

<%  if complete == true %>

  <%= f.label :age %><br>
  <%= f.number_field :age, class: "form-control-sm" %><br>

  <%= f.label :weight %><br>
  <%= f.number_field :weight, min: 0, class: "form-control-sm" %><br>

  <%= f.check_box :fixed, {:checked => false}, true, false %>
  <%= f.label "Fixed?" %><br>

  <%= f.label :friendly_rating %><br>
  <%= f.number_field :friendly_rating, in: 1...11, class: "form-control-sm" %><br>

  <%= f.label :aggressive_rating %><br>
  <%= f.number_field :aggressive_rating, in: 1...11, class: "form-control-sm" %><br>

  <%= f.label "Image URL" %><br>
  <%= f.text_field :img, class: "form-control-sm" %><br>

<% end %>
<br>

app/views/dogs/edit.html.erb
<h3>Modify your dog's details below.</h3>

<%= form_for @dog, url: user_dog_path(current_user, @dog) do |f| %>

  <%= render partial: "new_dog_form", locals: {f: f, complete: true}%>

  <%= f.submit "Update Dog", class: "btn btn-success btn-lg" %>
<% end %>

app/views/dogs/index.html.erb
<%= link_to "Add a dog", new_user_dog_path(current_user), class: "btn btn-success btn-lg" %><button id="sort-dog" class="btn btn-warning btn-sm pull-right" type="button" name="button">Sort (a-z)</button><br><br>

<div class="dogs-show">

</div>

<%= javascript_include_tag "dogs" %>

<script id="dogs-template" type="text/x-handlebars-template">
  {{#bootstrapRows 3 .}}
    <div class="row">
    {{#each .}}
    {{#imgLink .}}{{/imgLink}}
    <div class="dog col-lg-4 text-center mb-4">
      <img class="dog-img" src="{{img}}">
      <div class="overlay">
        <div class="bottom-text">
          <h3><a href="/users/{{userId}}/dogs/{{id}}" class="yellow-link">{{name}}</a></h3>
            {{age}} years old<br>
            {{weight}} lbs.<br>
            {{breed}}<br>
            {{sex}}<br>
        </div>
      </div>
    </div>
    {{/each}}
    </div>
  {{/bootstrapRows}}
</script>

app/views/dogs/new.html.erb
<h3>Enter your dog's details below.</h3>

<%= render partial: "layouts/show_errors", locals: {model: @dog} %>

<%= form_for @dog, url: user_dogs_path do |f| %>

  <%= render partial: "new_dog_form", locals: {f: f, complete: true}%>

  <%= f.submit "Add Dog", class: "btn btn-success btn-lg" %>
<% end %>

app/views/dogs/show.html.erb
<div class="dog-show" data-id="<%= @dog.id %>" data-uid="<%= @dog.user_id %>"></div>

<%= javascript_include_tag "play_date" %>
<%= javascript_include_tag "dog" %>

<script id="dog-template" type="text/x-handlebars-template">
    {{#imgLink .}}{{/imgLink}}
    <div class="dog col-lg-4 text-left mb-4">
      <a href="#" class="btn btn-outline-warning btn-sm" id="prevDog">< Previous Dog</a>
      <a href="#" class="btn btn-outline-warning btn-sm pull-right" id="nextDog">Next Dog ></a><br><br>
      <h2 class="yellow-text">{{name}}</h2>
      <img class="dog-img" src="{{img}}">
      <div class="">
            {{age}} years old<br>
            {{weight}} lbs.<br>
            {{breed}}<br>
            {{sex}}<br>
            Fixed? {{fixed}}<br>
            {{{friendlyIcons}}}<br>
            {{{aggressiveIcons}}}
      </div><br>
      <div class="play-dates">
        <h4 class="yellow-text">{{name}}'s Playdates</h4>
        <ul>
          {{#each playDates}}
            <li>{{{playDateIcons}}}<a href="/play_dates/{{id}}">{{{name}}}</a>
            <p class="indent-57">
              <i class="fas fa-map-marker-alt"></i><span class="indent-10">{{location}}<br>
              <i class="fas fa-calendar"></i><span class="indent-10">{{date}} at {{time}}</li>
            </p>
          {{/each}}
        </ul>
      </div>
      <a class="btn btn-success btn-lg" href="/users/{{userId}}/dogs/{{id}}/edit">Update Dog</a><br><br>
      <a data-confirm="Are you sure?" class="btn btn-danger btn-lg" rel="nofollow" data-method="delete" href="/users/{{userId}}/dogs/{{id}}">Remove Dog</a>
    </div>
</script>