config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/users/:id/my_play_dates' => 'play_dates#index', as: :my_play_dates
  get '/play_dates/past' => 'play_dates#past', as: :past_play_dates
  resources :users, only: [:new, :create, :show, :update, :edit] do
    resources :dogs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :play_dates, only: [:new, :create, :show, :update, :edit, :index, :destroy]
  resources :dog_play_dates, only: [:destroy, :create]
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/welcome' => 'welcome#welcome'
  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :require_login, only: [:welcome]

  def index
    redirect_to welcome_path if logged_in?
  end

  def welcome
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def last_five_play_dates
    PlayDate.last_five
  end
end

app/views/welcome/index.html.erb
<div class="text-center demo-parent">
  <h1 class="display-2 font-weight-bold">Welcome to Wagger.</h1>
  <h1 class="display-2 font-weight-bold"><i class="fas fa-dog"></i></h1>
  <h2>Wag better - <u>together</u>.</h2>
  <div class="demo">
      <br>
      <h2>Please use username: demo@demo.com and password: 123456 to demo this application.</h2>
      <button class="btn btn-success btn-lg" type="button" name="okay">Ok</button>
      <br><br>
  </div>
  <p class="lead"><br>
    <p><a class="btn btn-success btn-lg" href="<%= new_user_path %>" role="button">Sign Up</a></p>
    <p>or</p>
    <p><a class="btn btn-success btn-lg" href="<%= login_path %>" role="button">Log In</a></p>
    <p>or</p>
    <h3><%= link_to('<span id="white-fb">Log in with Facebook </span><i class="fab fa-facebook-square"></i>'.html_safe, '/auth/facebook') %></h3>
  </p>
</div>
<%= javascript_include_tag "index" %>

app/views/welcome/welcome.html.erb
<h1><strong>Welcome to Wagger, <%= current_user.name %>.</strong></h1>
<hr class="fade">
<p>Wagger provides a way to connect with other dog owners and to let all of our fuzzy friends to play!</p>
<p>Start by adding your dogs and joining an existing playdate, or, create a playdate of your own!</p><br>

<h5><strong>Newest playdates</strong></h5>
<%= render partial: "play_dates/play_date_list", locals: {playdates: last_five_play_dates } %>