config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/users/:id/my_play_dates' => 'play_dates#index', as: :my_play_dates
  get '/play_dates/past' => 'play_dates#past', as: :past_play_dates
  resources :users, only: [:new, :create, :show, :update, :edit] do
    resources :dogs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :play_dates, only: [:new, :create, :show, :update, :edit, :index, :destroy]
  resources :dog_play_dates, only: [:destroy, :create]
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/welcome' => 'welcome#welcome'
  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/play_date.rb
class PlayDate < ApplicationRecord
  belongs_to :user
  has_many :dog_play_dates
  has_many :dogs, through: :dog_play_dates

  accepts_nested_attributes_for :dog_play_dates, reject_if: :fields_blank?

  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :dog_limit, presence: true
  validates :dog_limit, numericality: true

  scope :current, -> { where('date >= ?', Date.current) }
  scope :past, -> { where('date < ?', Date.current) }
  scope :by_date, -> { order('date') }

  def format_date
    date.strftime("%B %d, %Y")
  end

  def format_time
    time.strftime("%l:%M %p")
  end

  def self.last_five
    order("created_at desc").limit(5)
  end

  def self.my_play_dates(id)
    where(user_id: id)
  end

  private

    def fields_blank?(attr)
      attr['dog_id'].blank?
    end

end

app/controllers/play_dates_controller.rb
class PlayDatesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :require_login
  before_action :play_date_owner?, only: [:destroy, :edit]
  after_action :header_vary, only: [:show, :index]

  def new
    @playdate = PlayDate.new
    current_user_dogs
  end

  def create
    @playdate = PlayDate.new(play_date_params)
    current_user_dogs
    save_play_date_or_show_error
  end

  def show
    find_play_date
    respond_to do |format|
      format.json { render json: @playdate }
      format.html { render 'play_dates/show' }
    end
  end

  def edit
    find_play_date
    current_user_dogs
  end

  def update
    find_play_date
    @playdate.update(play_date_params)
    redirect_to play_date_path(@playdate)
  end

  def index
    @playdate = PlayDate.new
    populate_play_dates
  end

  def past
    @playdate = PlayDate.new
    @playdates = PlayDate.past.by_date
    render "index"
  end

  def destroy
    find_play_date.destroy
    redirect_to play_dates_path
  end

  private

    def play_date_params
      params.require(:play_date).permit(:name, :location, :date, :time, :dog_limit, :user_id, :latitude, :longitude, dog_play_dates_attributes: [:id, :dog_id, :note])
    end

    def find_play_date
      @playdate = PlayDate.find(params[:id])
    end

    def play_date_owner?
      redirect_to root_path unless find_play_date.user_id == current_user.id
    end

    def current_user_dogs
      @dogs = current_user.dogs
    end

    def save_play_date_or_show_error
      if @playdate.save
        render json: @playdate, status: 201
      else
        render :json => { :errors => @playdate.errors.full_messages }
      end
    end

    def populate_play_dates
      if params[:id]
        @playdates = PlayDate.current.by_date.my_play_dates(params[:id])
      else
        @playdates = PlayDate.current.by_date
      end
    end

end

app/helpers/play_dates_helper.rb
module PlayDatesHelper
end

app/views/play_dates/_play_date_dog_fields.html.erb
<%= d.label :dog_id %><br>
<%= d.collection_select :dog_id, @dogs, :id, :name, :include_blank => show_blank %><br>

<%= d.label :note %><br>
<%= d.text_area :note, class: "form-control-sm" %><br>

app/views/play_dates/_play_date_fields.html.erb
<%= f.label :name %><br>
<%= f.text_field :name, class: "form-control-sm" %><br>

<%= f.label :location %><br>
<%= f.text_field :location, list: "location_list", class: "form-control-sm" %>
<datalist id="location_list" class="form-control-sm"><option value="Choose a location">Choose a location</option></datalist><br>

<%= f.label :date %><br>
<%= f.date_field :date, class: "form-control-sm" %><br>

<%= f.label :time %><br>
<%= f.time_field :time, class: "form-control-sm" %><br>

<%= f.label :dog_limit %><br>
<%= f.number_field :dog_limit, class: "form-control-sm" %><br>

<%= f.hidden_field :latitude %>
<%= f.hidden_field :longitude %>

app/views/play_dates/_play_date_list.html.erb
<ul>
  <% playdates.each do |p| %>
    <li>
      <% if p.user == current_user %>
        <i class="fas fa-user-edit"></i>
      <% else %>
        <i class="fas fa-user-edit invert"></i>
      <% end %> &nbsp
      <% if current_user.play_dates.include?(p) %>
        <i class="fas fa-calendar-check"></i>
      <% else %>
        <i class="fas fa-calendar-check invert"></i>
      <% end %>
      <a href="<%= play_date_path(p) %>" class="indent-10"><%= p.name %></a>

      <p class="indent-57">
        <i class="fas fa-map-marker-alt"></i><span class="indent-10"><%= "#{p.location}" %><br></span>
        <i class="fas fa-calendar"></i><span class="indent-10"><%= "#{p.format_date} at #{p.format_time}" %><br></span>
      </p>
    </li>
  <% end %>
</ul>

app/views/play_dates/_update_cancel_play_date.html.erb
<%= link_to 'Update Playdate',  edit_play_date_path(playdate), class: "btn btn-success btn-lg" if playdate.user == current_user %>

<%= link_to 'Cancel Playdate',  play_date_path(playdate), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" if playdate.user == current_user %>

<%= "<br><br>".html_safe if playdate.user == current_user %>

app/views/play_dates/edit.html.erb
<h3>Edit your playdate details below.</h3>

<%= form_for @playdate, url: play_date_path(@playdate) do |f| %>

  <%= render partial: "play_date_fields", locals: {f: f} %>

  <br>
  <%= f.submit "Update Playdate", class: "btn btn-success btn-lg" %>
<% end %>

app/views/play_dates/index.html.erb
<p><%= link_to "Create a New Playdate", new_play_date_path, class: "btn btn-success btn-lg", id: "playdate-new-button", data: {user_id: "#{current_user.id}"} %></p>

<div id="playdate-new">
  <h3>Enter your playdate details below.</h3>

  <div id="form-errors"></div>

  <%= form_for @playdate, url: play_dates_path do |f| %>

    <%= render partial: "play_date_fields", locals: {f: f} %>

    <%= f.hidden_field :user_id, :value => current_user.id %><br>

    <%= f.submit "Create Playdate", class: "btn btn-success btn-lg" %>
    <%= f.button "Cancel", class: "btn btn-danger btn-lg", id: "cancel-button" %><br><br>
  <% end %>
</div>

<%= render partial: "play_date_list", locals: {playdates: @playdates} %>

<div class="playdates-show" data-id="<%= @playdate.id %>" data-uid="<%= current_user.id %>"></div>

<%= javascript_include_tag "play_date" %>

<script id="playdate-template" type="text/x-handlebars-template">
  <ul>
    <li>
      {{{playDateIcons}}}<a href="/play_dates/{{id}}">{{name}}</a>
      <p class="indent-57">
        <i class="fas fa-map-marker-alt"></i><span class="indent-10">{{location}}<br>
        <i class="fas fa-calendar"></i><span class="indent-10">{{date}} at {{time}}
      </p>
    </li>
  </ul>
</script>

app/views/play_dates/new.html.erb
<h3>Edit your playdate details below.</h3>

<%= render partial: "layouts/show_errors", locals: {model: @playdate} %>

<%= form_for @playdate, url: play_dates_path do |f| %>

  <%= render partial: "play_date_fields", locals: {f: f} %>

  <%= f.hidden_field :user_id, :value => current_user.id %><br>

  <%= f.submit "Create Playdate", class: "btn btn-success btn-lg" %>
<% end %>

app/views/play_dates/show.html.erb
<%= render partial: "update_cancel_play_date", locals: {playdate: @playdate} %>

<div class="playdate-show" data-id="<%= @playdate.id %>" data-uid="<%= current_user.id %>"></div>

<%= form_for @playdate.dog_play_dates.build do |f| %>
  <%= f.label :dog_id, "Add your dog to this playdate" %><br>
  <%= f.collection_select :dog_id, current_user.dogs, :id, :name, :include_blank => false %><br>

  <%= f.label :note %><br>
  <%= f.text_area :note, class: "form-control-sm" %><br>

  <%= f.hidden_field :play_date_id %>

  <%= f.submit "Join Playdate", class: "btn btn-success btn-lg" %>
<% end %>

<%= javascript_include_tag "play_date" %>

<script id="playdate-template" type="text/x-handlebars-template">
  Name: {{name}}<br>
  Location: {{location}}<br>
  Date: {{date}}<br>
  Time: {{time}}<br>
  Dog Limit: {{dogLimit}}<br><br>
  Dog Participants:<br>
  <ol>
    {{#each playDates}}
      <li>
        <a href="/users/{{userId}}/dogs/{{dogId}}">{{dog}}</a> - "{{note}}" {{#deleteButton .}}{{/deleteButton}}<br>
      </li>
    {{/each}}
  </ol>
</script>
<br>
<p id='map'></p>